"""new tables for settings

Revision ID: 1ef666b8ad4e
Revises: 4ddec903a88e
Create Date: 2026-07-08 18:29:51.106839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef666b8ad4e'
down_revision: Union[str, Sequence[str], None] = '4ddec903a88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_markets_index',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('stock_market', sa.Enum('MOEX', name='stockmarketsnames', create_type=False), nullable=False),
                    sa.Column('index_name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_broker',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('broker_name', sa.Enum('T_BANK', name='brokernames', create_type=False), nullable=False),
                    sa.Column('broker_token', sa.String(), nullable=False),
                    sa.Column('sandbox', sa.Boolean(), nullable=False, server_default=sa.false()),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokers_account',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('users_broker_id', sa.UUID(), nullable=False),
                    sa.Column('account_name', sa.String(), nullable=False),
                    sa.Column('account_id', sa.String(), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['users_broker_id'], ['users_broker.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_strategy',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('strategy_type', sa.Enum('SHARE', 'BOND', name='strategiestype', create_type=False), nullable=False),
                    sa.Column('brokers_account_id', sa.UUID(), nullable=False),
                    sa.Column('stock_markets_index_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['brokers_account_id'], ['brokers_account.id'], ),
                    sa.ForeignKeyConstraint(['stock_markets_index_id'], ['stock_markets_index.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_strategy')
    op.drop_table('brokers_account')
    op.drop_table('users_broker')
    op.drop_table('stock_markets_index')
    # ### end Alembic commands ###


    op.execute('DROP TYPE IF EXISTS strategiestype')
    op.execute('DROP TYPE IF EXISTS brokernames')
    op.execute('DROP TYPE IF EXISTS stockmarketsnames')