name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - "docs/diagrams/*.puml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download PlantUML
        run: curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Generate diagrams
        run: |
          mkdir -p docs/imgs
          for f in docs/diagrams/*.puml; do
            java -jar plantuml.jar -tpng "$f" -o ../imgs
          done

      - name: Commit generated diagrams
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/imgs/*.png || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update diagrams"
            git push origin "$branch"
          fi
